### ISSUE TITLE
Viz

### ISSUE THREAD

**Issue by zenrabbit** [mgoldgisser/desert-fires-impact-biodiversity#4]
![Unknown](https://user-images.githubusercontent.com/4825462/181934428-74dccfc3-959e-4852-bd57-81223ccdb7aa.png)

count data you can use bars

and this second plot, what about the burn year +/-5 year?
![Unknown-1](https://user-images.githubusercontent.com/4825462/181934437-c4780b17-2f3e-4f92-b255-2d847b053de2.png)

**Comment by mgoldgisser** [comment]
https://mgoldgisser.github.io/desert-fires-impact-biodiversity/#recoveryD

added a plot for +/-5 years
![image](https://user-images.githubusercontent.com/64268022/182234554-2bd0a125-8042-4391-9018-134e5237a29e.png)
